### ISSUE TITLE
power-assert + vscode issue

### ISSUE THREAD

**Issue by atian25** [power-assert-js/power-assert#100]
hi, just let you know, we got a problem of `setBreakPoint` at `vscode` with `power-assert`.

https://github.com/Microsoft/vscode/issues/37199

> supports sourcemaps so you can debug as usual.

any  further information ?

**Comment by twada** [comment]
@atian25 Thank you for reporting!
Slow internet connection prevents me from updating VSC so I'll investigate your repro repo tomorrow.

**Comment by whxaxes** [comment]
@twada  Any progress ?

**Comment by atian25** [comment]
closed by https://github.com/Microsoft/vscode/issues/37199#issuecomment-479046473
