### ISSUE TITLE
Can't parse es2018 (for await)

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#106]
I want to use for-await syntax. Can you support es2018?

**Comment by twada** [comment]
@falsandtru Sorry for my late response. I'll tackle with this issue after #107. Thanks!

**Comment by falsandtru** [comment]
Thanks. Can you also update unassert? I can't use es2017+ in my projects because that can't parse it.

https://github.com/unassert-js/unassert/issues/12

**Comment by twada** [comment]
Will be fixed in forthcoming next minor release.

**Comment by twada** [comment]
[Just released as power-assert 1.6.0](https://github.com/power-assert-js/power-assert/blob/master/CHANGELOG.md#160-2018-06-14), thank you for reporting @falsandtru !
