### ISSUE TITLE
Missing * with async generator methods

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#110]
```js
// input
({
  async *g() {},
  async *[Symbol.asyncIterator]() {},
})
class C {
  async *g() {}
  async *[Symbol.asyncIterator]() {}
}
```

```js
// output
({
  async g() {},
  async [Symbol.asyncIterator]() {},
})
class C {
  async g() {}
  async [Symbol.asyncIterator]() {}
}
```

**Comment by falsandtru** [comment]
@twada

**Comment by falsandtru** [comment]
ping @twada

**Comment by falsandtru** [comment]
@twada ?

**Comment by twada** [comment]
It's nothing to do with power-assert but It's a escodegen's problem. I'm working on it.

**Comment by twada** [comment]
FYI: Just made a pull-req to escodegen
https://github.com/estools/escodegen/pull/375

**Comment by falsandtru** [comment]
Thanks.

**Comment by falsandtru** [comment]
@twada Looks like that fix isn't reflected because the dependencies and package-lock.json aren't updated. Can you update them and bump the version?

**Comment by twada** [comment]
@falsandtru 

1. I'm using optimistic semver range (a.k.a `^`)
2. package-lock.json only affects top-level install

So something is strange. I'm okay to bump and release but it's not a best solution here. We should rely on semver range.
Would you try cleaning `node_modules` and `package-lock.json` and install again?

**Comment by falsandtru** [comment]
Resolved. I'd tried to remove and install power-assert but it wasn't enough. Thanks.

**Comment by twada** [comment]
@falsandtru Glad to hear it 👍
