### ISSUE TITLE
assert.throws does not accept object

### ISSUE THREAD

**Issue by chadxz** [power-assert-js/power-assert#111]
as of Node.js v9+, the built-in [assert.throws()](https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message) accepts an object as the "error" parameter. When passed an object, it checks the properties of the error against the properties on the passed object.

Looks like power-assert does not currently support this. Would be great if it could be added!

**Comment by chadxz** [comment]
is this something you'd accept a PR to add?

**Comment by twada** [comment]
Thanks! I'll support `assert.throws` more in power-assert v2.
