### ISSUE TITLE
high-level assertions?

### ISSUE THREAD

**Issue by stephanos** [power-assert-js/power-assert#21]
I absolutely love, love, love power-assert.

One thing I'm a bit unsure about is how to test promises, though. In chai, for example, I can do

```
expect(promise).to.be.rejectedWith(...)
```

but with power-assert I need much more code. Is adding higher-level assertions on the roadmap, or can I build these myself somehow?

**Comment by twada** [comment]
Hi @stephanos,

> I absolutely love, love, love power-assert.

I'm very very glad to hear that :)

> but with power-assert I need much more code. Is adding higher-level assertions on the roadmap, or can I build these myself somehow?

In short term, sorry for the inconvenience for now.
Currently I don't have any roadmap to support Promises as a first citizen.

As you know, the core value of power-assert is absolute simplicity and stability.
power-assert API ought to be fully compliant with [standard assert interface](https://nodejs.org/api/assert.html).

Therefore, I'll support Promises as a first citizen
- when standard assert interface support Promises
- or, when I got an interface idea that is simple enough

However, it's a philosophy of power-assert official interface. So,

> or can I build these myself somehow?

I'll try to provide some extension mechanism to make users enhance power-assert!
Or I'll enhance chai-as-promised in a power-assert way ;)

**Comment by stephanos** [comment]
Thanks for the response! I'm looking forward to any further development :)
