### ISSUE TITLE
Support other assertion styles?

### ISSUE THREAD

**Issue by blai** [power-assert-js/power-assert#22]
e.g. `expect` and `should`

**Comment by twada** [comment]
> Support other assertion styles?
> e.g. expect and should

The answer is, sorry, No.

The core value of power-assert is absolute simplicity and stability.
Especially, power-assert sticks to the simplest form of testing. `assert(any expression)`

**Comment by blai** [comment]
No problem, thanks for providing your opinion. I just thought it would be cool to have additional options.
