### ISSUE TITLE
Async assertion does not work on (grunt?) karma when I use multiple karma preprocessors

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#26]
Async assertion is always successful under the this code.

```ts
    it('async assertion', function (done) {
      setTimeout(() => {
        console.log(assert(false === true), assert); // LOG: undefined, function powerAssert() { ... }
        done();
      }, 1);
    });
```

```js
// gruntfile.js
    karma: {
      options: {
        configFile: 'karma.conf.js',
        preprocessors: {
          'test/fixture/*.html': ['html2js'],
          'test/cov/*.js': ['coverage', 'espower']
        }
      },
      ph: {
        browsers: ['PhantomJS'],
        singleRun: true
      },
      dev: {
        browsers: ['PhantomJS'],
        preprocessors: {
          'test/cov/*.js': ['espower']
        },
        singleRun: false
      }
    },
```

```js
// karma.conf.js
    preprocessors: {
      'test/cov/*.js': ['coverage', 'espower']
    },
```

```
$ grunt karma:dev
```

以下詳細を英語がつたないので日本語で失礼します。
同期プロセスでのアサーションは正常に動作しますが非同期プロセスでは上記のとおり`assert(false === true)`が成功します。このバグは特殊な条件下で発生するようで、プリプロセッサの位置や組み合わせを変えると発生しません。grunt-karmaが内部的に生成するkarmaの設定が原因のような気がします。このバグが発生したプロダクトは未公開ですが対応していただけるようでしたら後ほど早めに公開してもってこようと思います。

**Comment by twada** [comment]
Hi @falsandtru, thank you for reporting!

Are you using [karma-coverage](https://github.com/karma-runner/karma-coverage)?
I recommend you to NOT to use `espower` after `coverage`. Both of them modify AST so they may not work as expected.

Solution here is just remove `espower` from configuration for coverage.
When `espower` preprocessor is not specified, power-assert works as normal assert.
```
// karma.conf.js
    preprocessors: {
      'test/cov/*.js': ['coverage']
    },
```
If this does not work, then it's not a problem of power-assert (because there is no AST transformation caused by power-assert).

Please try this config!

Of course I'll try to debug combination of `coverage` and `espower` and see what happens.

**Comment by falsandtru** [comment]
Thanks for your help. Yes, I am using karma-coverage. But this is not easy problem of preprocessor combination because this setting resolve the bug. This is problem of setting structure.

プリプロセッサを複数噛ませた影響というのはもちろん検証したのですが以下の設定ではバグが発生しないので単純に多段変換が原因でもないようです。率直に言って、両方のプリプロセッサを同時利用することはできており、設定の構成方法によってバグが発生しています。また、`$ karma start`でkarmaを直接起動してもバグが発生しません。

```js
// gruntfile.js
    karma: {
      options: {
        configFile: 'karma.conf.js',
        preprocessors: {
          'test/fixture/*.html': ['html2js'],
          'test/cov/*.js': ['coverage', 'espower']
        }
      },
      ph: {
        browsers: ['PhantomJS'],
        singleRun: true
      },
      dev: {
        browsers: ['PhantomJS'],
        singleRun: false
      }
    },
```

I want measures as a fail-safe.

挙動から推測してpower-assertが直接原因である可能性は低いと思いますが、バグの出方がいやらしく気づきにくいためなんらかのフェイルセーフとしての対策を講じていただけないかと思いここに書かせていただきました。セルフチェックをするなどして完全に動くか完全に動かないか、あるいは警告を表示して異常に気づけるようにしていただけると助かります。また、テストとカバレッジの組み合わせは典型的なユースケースなので可能であれば対応願います。以上が概要で、power-assertの明白なバグともいい難いのでここでいったんcloseさせていただきます。さらに情報が必要な場合はreopenしてご連絡ください。

追記：`assert(false)`なら正常に動作します。非同期かつ評価式を入れると動作しないようです。

このバグを検出するためのテストを残しておきます。設定を変更して運悪く偶然このバグが発露しても検知できるようになります。

```js
// Detect the assertion bug
    it('assertion self-check', function (done) {
      setTimeout(function () {
        try {
          console.log(assert(false === true), assert); // LOG: undefined, function powerAssert() { ... }
        }
        catch (e) {
          done();
          return;
        }
        throw new Error('WARNING!: assert function does not work.');
      }, 1);
    });
```

**Comment by twada** [comment]
Thanks a lot for your detailed report and feature suggestions!
