### ISSUE TITLE
Incorrect `instanceof` assertion messages

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#27]
expected

```
  assert(null instanceof Object)
              |          |
              false      #function#
```

```
  assert(void 0 instanceof Object)
         |      |          |
         |      false      #function#
         undefined
```

actual

```
  assert(null instanceof Object)
         |               |
         false           #function#
```

```
  assert(void 0 instanceof Object)
         |                 |
         |alse             #function#
         undefined
```

**Comment by twada** [comment]
@falsandtru Thank you for reporting! This is a bug. I'll fix it ASAP.

**Comment by twada** [comment]
Oops, this issue will be closed when power-assert-formatter is released.
To be released soon.

**Comment by twada** [comment]
Close this issue again since [power-assert 1.0.1 is released.](https://github.com/power-assert-js/power-assert/blob/master/CHANGELOG.md#101-2015-09-14)

**Comment by falsandtru** [comment]
Lightning fix! Thanks!

**Comment by twada** [comment]
@falsandtru You're welcome! Thank you for reporting this bug :smiley:
