### ISSUE TITLE
String comparing

### ISSUE THREAD

**Issue by TrySound** [power-assert-js/power-assert#31]
Hi. I need to compare multiline strings but the output is too hard to analyze. It the a way to make it more visual. For example [fast-diff](https://github.com/jhchen/fast-diff) seems interesting.

The second problem is compare on windows. When read input or output from disk it contains `\r\n` linebreaks. Every time I should to add `.replace(/\r\n/g, '\n')`

**Comment by twada** [comment]
Hi @TrySound , thank you for your opinion. I understand.

`power-assert` is designed to be run under any environments, from old browsers to modern console, so I could not give universal fancy diffs yet (assuming only mono-color environment).

If you are using power-assert via AVA, you may be using modern console. If you only use AVA through console, customized renderer may help. I'm going to provide customized renderer for AVA users.

refs: [Objects are difficult to differentiate. · Issue #1 · twada/power-assert-renderers](https://github.com/twada/power-assert-renderers/issues/1)

So, I'm sorry for inconvenience. I'll work on this soon.

FYI: if you compare two strings by `===`, power-assert will show you [Line level diffs](https://github.com/power-assert-js/power-assert-formatter/blob/5c02df56a75b2e404b9ad21d5e52e6f9f5aafcb3/test/power_assert_formatter_test.js#L1538-L1566) by [google-diff-match-patch](https://code.google.com/p/google-diff-match-patch/). This feature might be help you (it's not a friendly enough though).


> The second problem is compare on windows

Sorry, I have no idea to solve this. Some filtering/converting libraries may help.
