### ISSUE TITLE
JSX Support

### ISSUE THREAD

**Issue by jamestalmage** [power-assert-js/power-assert#34]
Reference: 
  https://github.com/sindresorhus/ava/issues/274

**Comment by twada** [comment]
Now I'm working with it.

refs: [[WIP][experimental] Big refactoring: Embed assertion's AST and tokens to make runtime side parser unnecessary](https://github.com/power-assert-js/babel-plugin-espower/pull/13)

**Comment by MoOx** [comment]
@twada I saw that the PR you mentionned has been merged. What is the progress on this issue then?

**Comment by twada** [comment]
@MoOx 
If you are using AVA, you can use JSX tags once [this PR](https://github.com/avajs/ava/pull/903)  has been released.
If you are using power-assert directly, you can now use JSX tags through babel-plugin-espower with option `embedAst: true`.

**Comment by twada** [comment]
To be documented though.

**Comment by twada** [comment]
Close this issue since this feature is [documented](https://github.com/power-assert-js/babel-plugin-espower#optionsembedast), and power-assert also [suggests configuration option on parse error](https://github.com/twada/power-assert-runtime/pull/15).
