### ISSUE TITLE
Assertion error messages have local file paths

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#39]
An assertion message has a local file path instead of variables.

expected:

```
assert(!!database_ === true);
       |||         |
       ||undefined false
       |true
       false
```

actual:

```
assert(!!dataD:/<dir>/<file>_ === true)
       |||         |
       ||undefined false
       |true
       false
...
... /power-assert.js:6093)
```

**Comment by twada** [comment]
@falsandtru power-assert does not modify original expression, only canonicalize it in one line format.
So I think it is not by power-assert but some other npm module.

The output `assert(!!dataD:/<dir>/<file>_ === true)` seems that some module has replaced the word `base` with your project dir (`database_` => `dataD:/<dir>/<file>_`)

**Comment by falsandtru** [comment]
I use karma-espower-preprocessor. Is this a cause?

**Comment by twada** [comment]
> I use karma-espower-preprocessor. Is this a cause?

I don't think so. In your output,

```
assert(!!dataD:/<dir>/<file>_ === true)
       |||         |
       ||undefined false
       |true
       false
```

vertical bar for `===` is out of alignment.
This means that the replacement (`database_` => `dataD:/<dir>/<file>_`) has occurred __after__ the power-assert processing.
If power-assert and related modules are wrong, the vertical bar will match.

So some reporter module for karma would be the criminal.

**Comment by falsandtru** [comment]
Now I can reproduce this problem in my repository(however, this is complex). Can you test that repository?

**Comment by twada** [comment]
Thanks for repro case. However I don't have enough time now so I review it in a few days.

**Comment by falsandtru** [comment]
Thanks. This is details.

```js
assert(!database_ === true);
```

```js
            assert(assert._expr(assert._capt(assert._capt(!assert._capt(database_, 'arguments/0/left/argument'), 'arguments/0/left') === true, 'arguments/0'), {
                content: 'assert(!database_ === true)',
                filepath: 'D:/<path>',
                line: 40
            }));
```

Strange to say, I got correct assertion messages from browser, but I got wrong assertion messages from terminal.

I will provide repro in January ASAP.

Windows7 x64

**Comment by twada** [comment]
@falsandtru Any advance on this issue?

**Comment by falsandtru** [comment]
Sorry, I close this issue because I overwrote that code. I think this problem probably caused by terminal. Thanks for the response.

**Comment by twada** [comment]
@falsandtru Okay, thanks :)
