### ISSUE TITLE
TypeError: assert._capt is not a function

### ISSUE THREAD

**Issue by searls** [power-assert-js/power-assert#42]
I tried to add this really simply to my vanilla Node.js module using intelli-espower-loader, but right from the jump I got this error: "TypeError: assert._capt is not a function"

Any root causes?

To reproduce, you can check out this repo at this commit: https://github.com/testdouble/scripty/commit/4a00d0f27248c6ac38cce17c53c5a43f1a031ce1

**Comment by twada** [comment]
I assume that you are still using normal `assert` module, not `power-assert`.

Please change [here](https://github.com/testdouble/scripty/blob/master/test/unit-helper.js#L2) from
```js
global.assert = require('assert')
```
to
```js
global.assert = require('power-assert')
```

**Comment by searls** [comment]
Ohhhhh, duh. Thank you.

**Comment by twada** [comment]
[Added to FAQ](https://github.com/power-assert-js/power-assert/commit/3de6b08baa7e88926451098b582e82238e964b57). Thanks!

**Comment by twada** [comment]
FYI: if you are using Babel, you can use [babel-plugin-empower-assert](https://www.npmjs.com/package/babel-plugin-empower-assert) to solve this problem.

With [babel-plugin-empower-assert](https://www.npmjs.com/package/babel-plugin-empower-assert), you can enhance normal `assert` to `power-assert` with `.babelrc` settings.

```js

{
  "presets": [
    . . .
  ],
  "env": {
    "development": {
      "plugins": [
        "babel-plugin-empower-assert",
        "babel-plugin-espower"
      ]
    }
  }
}
```

**Comment by searls** [comment]
Thanks @twada. To be honest I still wasn't able to get past this bug when writing a vanilla library. I tried using the "intelli" loader and then power-assert but it didn't work. My only theory is that maybe the loader has to be loaded _in a separate file_ from any requires of power-assert?

The repo in question is the same one: github.com/testdouble/scripty if you have a minute to advise me (I'm using a very minimal testing lib that doesn't provide much abstraction)

**Comment by twada** [comment]
@searls Thank you for your question. I've cloned your repo and enabled power-assert.
Your [scripty/decorate-assertions.js](https://github.com/testdouble/scripty/blob/874d2622aa7bec76ba28ba58a573c1bd025f4794/test/decorate-assertions.js) is tricky a bit so I should use my [WIP branch of espower](https://github.com/power-assert-js/espower/pull/26)

Here is the patch.

```patch
diff --git a/package.json b/package.json
index 93aaeee..938157b 100644
--- a/package.json
+++ b/package.json
@@ -30,7 +30,10 @@
   },
   "homepage": "https://github.com/testdouble/scripty#readme",
   "devDependencies": {
+    "espower": "power-assert-js/espower#embedded-recorder",
+    "espower-loader": "^1.0.0",
     "intercept-stdout": "^0.1.2",
+    "power-assert": "^1.3.1",
     "rimraf": "^2.5.2",
     "semver": "^5.1.0",
     "standard": "^6.0.8",
diff --git a/test/safe-helper.js b/test/safe-helper.js
index 118208e..21a2d6b 100644
--- a/test/safe-helper.js
+++ b/test/safe-helper.js
@@ -1,5 +1,10 @@
+require('espower-loader')({
+  cwd: process.cwd(),
+  pattern: 'test/safe/**/*.js'
+})
+
 var decorateAssertions = require('./decorate-assertions')
-global.assert = decorateAssertions(require('assert'))
+global.assert = decorateAssertions(require('power-assert'))
 
 var log = require('../lib/log')
 
diff --git a/test/unit-helper.js b/test/unit-helper.js
index c695b96..700cb61 100644
--- a/test/unit-helper.js
+++ b/test/unit-helper.js
@@ -1,7 +1,12 @@
+require('espower-loader')({
+  cwd: process.cwd(),
+  pattern: 'lib/**/*.test.js'
+})
+
 global.td = require('testdouble')
 
 var decorateAssertions = require('./decorate-assertions')
-global.assert = decorateAssertions(require('assert'))
+global.assert = decorateAssertions(require('power-assert'))
 
 var log = require('../lib/log')
 
```

Thanks.

**Comment by popomore** [comment]
Same question, why can't use intelli-espower-loader with assert?

**Comment by twada** [comment]
@popomore Now you can use intelli-espower-loader (espower-loader) with `assert`

see: [espower-loader's CHANGELOG](https://github.com/power-assert-js/espower-loader/blob/master/CHANGELOG.md#110-2016-11-12)

**Comment by popomore** [comment]
@twada Good Job
