### ISSUE TITLE
power-assert make `assert()` of assert module silent

### ISSUE THREAD

**Issue by azu** [power-assert-js/power-assert#43]
I've created reproduce repository.

- https://github.com/azu/issue-power-assert-with-assert

Application code use `assert` module of Node Core.

`index.js`
```js
// application code use `assert` module
const assert = require("assert");
export function hello(name) {
    assert(typeof name === "string");
    return "Hello " + name;
}
```

Test code: 

```js
const assert = require("power-assert");
import {hello} from "../src/index";
describe("hello", function () {
    it("should accept string", function () {
        hello(42);  // Should throw error via assert and fail tests.
    });
});
```

These code are transformed by babel + babel-plugin-espower.

`.babelrc`

```json
{
  "presets": [
    "es2015"
  ],
  "env": {
    "development": {
      "plugins": [
        "babel-plugin-espower"
      ]
    }
  }
}
```

When I do this:

```
npm test
```

### Expected

Fail test

### Actual

Pass test :(

-----

### Reason 

Application code is transformed to

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };

var _powerAssertRecorder = function () { function PowerAssertRecorder() { this.captured = []; } PowerAssertRecorder.prototype._capt = function _capt(value, espath) { this.captured.push({ value: value, espath: espath }); return value; }; PowerAssertRecorder.prototype._expr = function _expr(value, source) { return { powerAssertContext: { value: value, events: this.captured }, source: source }; }; return PowerAssertRecorder; }();

exports.hello = hello;
// application code use `assert` module
var assert = require("assert");
function hello(name) {
    var _rec = new _powerAssertRecorder();

    assert(_rec._expr(_rec._capt(_rec._capt(typeof name === "undefined" ? "undefined" : _typeof(name), "arguments/0/left") === "string", "arguments/0"), {
        content: "assert(typeof name === \"string\")",
        filepath: "src/index.js",
        line: 4
    }));
    return "Hello " + name;
}
//# sourceMappingURL=index.js.map
```
`_rec._expr` return object.

```js
    var assert = require("assert");
    var object = _rec._expr(_rec._capt(_rec._capt(typeof name === "undefined" ? "undefined" : _typeof(name), "arguments/0/left") === "string", "arguments/0"), {
        content: "assert(typeof name === \"string\")",
        filepath: "src/index.js",
        line: 4
    });
    assert(object);
```

So, `assert(Object)` never throw error. It causes this issue. 

Do you have any solution?

**Comment by twada** [comment]
@azu Thank you for reporting.
Ah, that's a problem... One thing I can do is, to convert `require('assert')` to `require('power-assert')`.
I'll create a small babel plugin to do the transpilation.
Thanks!

**Comment by twada** [comment]
@azu Just created and published [babel-plugin-empower-assert](https://www.npmjs.com/package/babel-plugin-empower-assert) to solve this problem. Would you give it a try?

**Comment by twada** [comment]
Made a [pull-req](https://github.com/azu/issue-power-assert-with-assert/pull/1) for you.

**Comment by azu** [comment]
@twada Thanks. work find.

I think that this issue should be added to [FAQ](https://github.com/power-assert-js/power-assert#faq "FAQ"), because this solution is **opt-in**.

If a user encounter this issue, the use see [FAQ](https://github.com/power-assert-js/power-assert#faq "FAQ") at first, I think.

**Comment by twada** [comment]
> I think that this issue should be added to FAQ, because this solution is opt-in.
If a user encounter this issue, the use see FAQ at first, I think.

Yeah exactly!

**Comment by twada** [comment]
FYI: if you are using Babel, you can use [babel-plugin-empower-assert](https://www.npmjs.com/package/babel-plugin-empower-assert) to solve this problem.

With [babel-plugin-empower-assert](https://www.npmjs.com/package/babel-plugin-empower-assert), you can enhance normal `assert` with `.babelrc` settings below.

```js

{
  "presets": [
    . . .
  ],
  "env": {
    "development": {
      "plugins": [
        "babel-plugin-empower-assert",
        "babel-plugin-espower"
      ]
    }
  }
}
```

**Comment by twada** [comment]
Added to FAQ as [How to deal with `assert` calls in production](https://github.com/power-assert-js/power-assert/commit/1341bca3df0af6350404df3020c49309aaacc6b7).

**Comment by azu** [comment]
Thanks again.

**Comment by twada** [comment]
You're welcome ;)
