### ISSUE TITLE
webpack use the legacy assert ( `deepStrictEqual` is not a function )

### ISSUE THREAD

**Issue by 59naga** [power-assert-js/power-assert#45]
when use the `power-assert@1.3.1` from `webpack@1.12.14` / `babel-loader@6.2.4`, doesn't have the `deepStrictEqual`, it seems old `assert` is used.

```js
import assert from 'assert';
import moduleName from '../src';

describe('moduleName', () => {
  it('spec1', () => {
    assert.deepEqual(moduleName(), { foo: null });// pass
    assert.deepStrictEqual(moduleName(), { foo: null });// error
  });
});
```

simulation environment: https://github.com/59naga/boilerplate-browser-babel

```bash
git clone https://github.com/59naga/boilerplate-browser-babel
cd boilerplate-browser-babel
git checkout 4804fd5432c626268ca2f148bc58e15bed7c0ec5

npm install
node -v && npm -v
# v5.10.0
# 3.8.3
npm test
# TypeError: _powerAssert2.default.deepStrictEqual is not a function
#        at Context.<anonymous> (/Users/59naga/Downloads/boilerplate-browser-babel/test/index.js:71:28 <- webpack:///test/index.js:10:11)
```

one workaround,  frozen the version of `assert` in `4.1.2` using the [core-assert](https://github.com/59naga/power-assert/commit/1046e66da2a2c5be16988620ee68b43613450d33).

```bash
npm install 59naga/power-assert
npm test
# ...
# AssertionError:   # test/index.js:11
#
#   assert.deepStrictEqual(moduleName(), { foo: null })
#                          |                 |
#                          |                 Object{foo:null}
#                          Object{foo:undefined}
```

other than this, would you have any good solution?

> 英語に自信がないので、翻訳前の日本語も残しておきます。
> `webpack`/`babel-loader`から`power-assert`を使用すると、`deepStrictEqual`を持たない、古い`assert`が使用されるようです。
> 解決方法の一つとして、[core-assert](https://github.com/59naga/power-assert/commit/1046e66da2a2c5be16988620ee68b43613450d33)に依存し、`assert`のバージョンを`4.1.2`に固定する方法があります。
> これ以外で、何か良い解決方法はご存知でしょうか？

**Comment by twada** [comment]
@59naga Thank you for reporting!

> it seems old assert is used.

Hmm, I'll take a look...
Maybe webpack might be using [commonjs-assert](https://www.npmjs.com/package/assert) as a polyfill?
If so, depending on [core-assert](https://www.npmjs.com/package/core-assert) might help.

**Comment by falsandtru** [comment]
I also want to use deepStrictEqual on browsers (without webpack). Can power-assert use another assertion library that has a deepStrictEqual method?

**Comment by falsandtru** [comment]
@59naga I am unable to get descriptive assertion messages on browsers using your fixes (https://github.com/59naga/power-assert/commit/1046e66da2a2c5be16988620ee68b43613450d33). Can you get descriptive assertion messages on browsers?

**Comment by falsandtru** [comment]
Sorry, it probably does not depend this issue.

**Comment by twada** [comment]
@59naga @falsandtru Sorry for my late response.

Now I understand the issue. Both Webpack and Browserify use [commonjs-assert](https://www.npmjs.com/package/assert) as browser polyfill and it does not have `deepStrictEqual`.

**Comment by twada** [comment]
FYI: I've created [universal-deep-strict-equal](https://github.com/twada/universal-deep-strict-equal), a port of Node v6's internal _deepEqual function in a universal style, and I'm trying to integrate this into power-assert.
