### ISSUE TITLE
Unable to get descriptive assertion messages on browsers

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#46]
Does power-assert provide descriptive assertion messages on browsers?

Code

```js
assert(0 === 1);
assert.deepEqual({foo: 0}, {foo: 1});
```

Expected(node)

```
          assert(0 === 1)
                   |
                   false
  assert.deepEqual({ foo: 0 }, { foo: 1 })
                   |           |
                   |           Object{foo:1}
                   Object{foo:0}
```

Actual(browser)

```
          assert(0 === 1)
                   |
                   false
        AssertionError: {"foo":0} deepEqual {"foo":1}
```

**Comment by falsandtru** [comment]
espowerd on browsers

```js
                assert(assert._expr(assert._capt(0 === 1, 'arguments/0'), {
                    content: 'assert(0 === 1)',
                    filepath: 'D:/develop/personal/component/arch-stream/dist/arch-stream.js',
                    line: 2751
                }));
                assert.deepEqual({ foo: 0 }, { foo: 1 });
```

It seems a convert leak.

**Comment by twada** [comment]
This is expected behaviour.

`assert.deepEqual({foo: 0}, {foo: 1})`
That are `ObjectExpression`s having only `Literal`s.
power-assert does not capture `Literal`s since we can see their values as-is.

If the expression has some `Identifier`s, then power-assert tries to capture them.
`assert.deepEqual({foo: bar1}, {foo: bar2})`

**Comment by falsandtru** [comment]
In short, power-assert does not provide descriptive assertion messages on browsers?

```
AssertionError: {"foo":0} deepEqual {"foo":1}
```

I want to get a following assertion message.

```
  assert.deepEqual({ foo: 0 }, { foo: 1 })
                   |           |
                   |           Object{foo:1}
                   Object{foo:0}
```

**Comment by twada** [comment]
@falsandtru The point you suggested is correct.
That is strange...I'll investigate it.
What instrumentor are you using for browsers?
(gulp-espower, espowerify, babel-preset-power-assert, ...)

**Comment by falsandtru** [comment]
You can repro this problem on my repo https://github.com/falsandtru/arch-stream .

0. clone repo.
0. npm i && gulp install && gulp watch
0. add test code to somewhere(e.g. https://github.com/falsandtru/arch-stream/blob/master/test/interface/package.ts#L25).

**Comment by falsandtru** [comment]
Fixed by https://github.com/power-assert-js/karma-espower-preprocessor/pull/1
