### ISSUE TITLE
assert.deepEqual() with tolerance

### ISSUE THREAD

**Issue by Turbo87** [power-assert-js/power-assert#58]
I would like to use `assert.deepEqual()` to compare two JSON objects, but the objects contain floating-point numbers that are only roughly the same. Is there some way to compare those two objects with a tolerance when comparing numbers? i.e. when the algorithm compares numbers it will accept a difference of up to 0.001% or something like that.

**Comment by twada** [comment]
@Turbo87 Thank you for your question.

`power-assert` aims to be completely compliant to [Node.js Assert API](https://nodejs.org/api/assert.html). Therefore, API issues and improvements should be done in [Node.js](https://github.com/nodejs/node/issues) first.

When I compare two floating point values, single value comparison would look like:

```js
assert(Math.abs(actual - expected) < Number.EPSILON);
```

However here you want to compare two deep structure having floating point values somewhere.
In that case, unfortunately, you are forced to create your own `deepEqualWithTolerance` function.
(see [universal-deep-strict-equal](https://github.com/twada/universal-deep-strict-equal))

```js
assert(deepEqualWithTolerance(actual, expected, tolerance));
```

BTW, you can use `JSON.stringify` __if and only if__ two objects and its value conversion logic is simple enough.

```js
function tolerant (obj) {
    return JSON.parse(JSON.stringify(obj, function replacer(key, value) {
        if (typeof value === 'number') {
            return (YOUR VALUE CONVERSION LOGIC HERE);
        }
        return value;
    }));
}

var expected = {
    deep: {
        val: 0.3
    }
};
var actual = {
    deep: {
        val: 0.2 + 0.1
    }
};
assert.deepEqual(tolerant(actual), tolerant(expected));
```

**Comment by Turbo87** [comment]
> In that case, unfortunately, you are forced to create your own deepEqualWithTolerance function.

I was afraid of that... I guess in that case I won't get any special power-assert diffing magic though, correct?

**Comment by twada** [comment]
> I guess in that case I won't get any special power-assert diffing magic though, correct?

Correct.

**Comment by twada** [comment]
Closed this issue since this is not related to power-assert feature.
