### ISSUE TITLE
Usage in Labjs

### ISSUE THREAD

**Issue by feugy** [power-assert-js/power-assert#61]
Hello, and thank you for this wonderful library !

We use [lab](https://github.com/hapijs/lab) a lot for testing. And it's as easy to use Power-assert with lab that it is with mocha.

I'd like to share the transform file needed to activate Power-assert, and I wonder the best way to do it.
1- Do I create a project (like you did with espower-loader) under my account ?
2- Do you create an empty project, so I can send you a PR ?
3- Do I send you the file (20 lines) and instructions ?

Thank you again !

**Comment by twada** [comment]
@feugy Wow that's great! Thank you!
Please feel free to create your own project. I'm happy to link it from power-assert README.

**Comment by feugy** [comment]
Hello @twada. The [repo](https://github.com/feugy/lab-espower-transformer) is ready, and a first version is [published](https://www.npmjs.com/package/lab-espower-transformer) on npm.
As you can see, it's really little work, and I'm happy we can now use it with Lab.

I'll get in touch with the Hapi community to promote power-assert.

**Comment by twada** [comment]
@feugy Made a link to [lab-espower-transformer](https://github.com/feugy/lab-espower-transformer) from power-assert README. Thanks a lot!
