### ISSUE TITLE
deepStrictEqual more descriptive output when failing

### ISSUE THREAD

**Issue by gpcboekema** [power-assert-js/power-assert#63]
There seems to be lacking output for assert.deepStrictEqual compared to assert.deepEqual.
If you provide a 'descriptive message when assertion is failed' only that message will be printed:

`descriptive message`

If you don't provide a message to the method, the compared objects will be printed like this:

`{object1} deepStrictEqual {object2}` 

But in both cases you want to be able to compare them in the output (somewhat like deepEqual).

Besides this if the objects (that are compared) are somewhat 'big' they wont display completely (when not providing a message):

`{"startupExtent":{"extent":[139722.24000000002,407339.51999999996,159774.72,416102.39999999997],"srs":"EPSG:28992"},"userSrs":"E deepStrictEqual {"startupExtent":{"extent":[139722.24000000002,407339.51999999996,159774.72,416102.39999999997],"srs":"EPSG:28992"},"userSrs":"E`

actual object:
```var object = {
                    startupExtent: {"extent":[139722.24000000002,407339.51999999996,159774.72,416102.39999999997],"srs":"EPSG:28992"},
                    userSrs: 'EPSG:28992',
                    searchHistory: [],
                    mapShowScaleBarDefault: true,
                    mapShowZoomSliderDefault: true,
                }```

**Comment by twada** [comment]
@gpcboekema Thank you for reporting.

`{object1} deepStrictEqual {object2}` is a default output of normal assert module.
Therefore, it seems that your code is not transpiled by one of power-assert's instrumentors, or version of instrumentor you are using is old.

Please make sure to use one of instrumentors below, and its version is new enough.
`assert.deepStrictEqual` support is relatively new so upgrading your instrumentor may help.

- babel-plugin-espower
- babel-preset-power-assert
- intelli-espower-loader
- espower-loader
- espowerify
- webpack-espower-loader.
- gulp-espower
- grunt-espower
- karma-espower-preprocessor
- espower-cli

If you are already using instrumentor, would you tell me your environments?

- OS
- Node version
- power-assert related module version

**Comment by gpcboekema** [comment]
@twada Thank you for your answer.

Updating karma-espower-preprocessor solved the problem.

We were at karma-espower-preprocessor version 0.0.4 and updating to a major release (1.1.0) isn't just an npm update, so we missed that one.

Thanks again.

**Comment by twada** [comment]
@gpcboekema I'm glad to hear that 😃
