### ISSUE TITLE
Power assert with ts-node

### ISSUE THREAD

**Issue by studds** [power-assert-js/power-assert#65]
I prefer to use [ts-node](https://github.com/TypeStrong/ts-node) along with power assert, as I've already worked out how to get ts-node running the way I like.

I ran in to a few hurdles along the way, and created a new module to get ts-node working together with power-assert: https://github.com/tracecomms/espower-ts-node

The main thing I couldn't figure out was how to ignore errors and do a fast transpile instead of full type checking - which I find useful during dev, as it's quite a bit faster.

I know this is not really an issue as such, but though I'd add it here as I spent quite a bit of time trying to work this out, and hopefully either a) someone can let me know the simple solution I missed or b) this will help someone else!

Thanks for the amazing tool :-)

**Comment by twada** [comment]
@studds Thanks! I'm very glad to see ts-node working together with power-assert.
So I made a link to [espower-ts-node](https://github.com/tracecomms/espower-ts-node) from README.

(I'm sorry that I cannot advice you since I'm not a TypeScript user...)

**Comment by studds** [comment]
Thanks @twada

**Comment by twada** [comment]
closed via 82a0e9336
