### ISSUE TITLE
assert.deepEqual and truthy values

### ISSUE THREAD

**Issue by feugy** [power-assert-js/power-assert#68]
It seems that equals isn't always using strict equality:
```javascript
assert.deepEqual({methodology: true}, {methodology: 1}) // doesn't fail
assert.equal(true, 1) // doesn't fail
```

Is it intended ?

**Comment by feugy** [comment]
My bad, it is.

As I'm used to chai, I didn't knew that [assert](https://nodejs.org/api/assert.html) specificity.

**Comment by twada** [comment]
@feugy That's right. Please use `assert.deepStrictEqual` for this purpose ;)
