### ISSUE TITLE
Support TypeScript 2.0

### ISSUE THREAD

**Issue by danielmoore** [power-assert-js/power-assert#69]
Just cross posting - power-assert-js/espower-typescript#18 hasn't been touched in over two weeks now. Can anyone here merge and publish it?

**Comment by twada** [comment]
@danielmoore Thank you for pinging!
@teppeis @vvakame Would you take a look?

**Comment by teppeis** [comment]
@twada @danielmoore ok, I'll check it!

**Comment by teppeis** [comment]
Fixed in espower-typescript v6.0.0. Thanks!
