### ISSUE TITLE
any tool to migrate `should/expect` code to `power-assert`?

### ISSUE THREAD

**Issue by atian25** [power-assert-js/power-assert#74]
power-assert is amazing

**Comment by watilde** [comment]
Hello! No, we don't have it, but it would be not hard to do manually since power-assert has only method `assert`.

**Comment by atian25** [comment]
but `should` is complex, such as:
- `should.be.ok(someVar)` 
- `someKey.should.not.exist()`
- `someKey.should.eql('aaa')`
- `should.throw(() => {})`

**Comment by watilde** [comment]
Yeah, it's complicated and multifunctional indeed. Well, the behaviour of the `should/expect` could depend on the tools/its syntax design, and that's why I think the migration topic could be out of the scope of this project, IMO.

**Comment by twada** [comment]
@atian25 @watilde Good feature request. It's good to have migration path to assert.

Just begun [chai-to-assert](https://github.com/twada/chai-to-assert), a jscodeshift codemod that transforms from chai to assert, still highly experimental ;)

**Comment by atian25** [comment]
hey, just let you know, found a way to handler this issue:

https://github.com/cpojer/js-codemod/blob/master/transforms/expect.js

**Comment by atian25** [comment]
https://github.com/node-modules/should2assert

**Comment by twada** [comment]
@atian25 Wow great! Now we have migration paths from both should.js and chai!

**Comment by twada** [comment]
Tools available:

- [twada/chai-to-assert: A jscodeshift codemod that transforms from chai to Node assert](https://github.com/twada/chai-to-assert)
- [node-modules/should2assert: A tool to help you migrating from should to assert](https://github.com/node-modules/should2assert)
- [twada/expect-js-to-assert: A jscodeshift codemod that transforms from expect.js to Node assert](https://github.com/twada/expect-js-to-assert)
