### ISSUE TITLE
Disallow assignments in assertions

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#77]
It should let me know as errors.

```js
assert(n === 0); // intended
assert(n = 0); // mistake, should be an error
```

**Comment by azu** [comment]
I think that it is not power-asssert(assert)'s task.
(This feature change assertion behavior and is not compatible Node.js `assert()` function.)

It will be checked by Linter like ESLint.

- [no-cond-assign - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/no-cond-assign "no-cond-assign - Rules - ESLint - Pluggable JavaScript linter") is similar rule.

You can create that as ESLint plugin, Babel plugin and other.

**Comment by falsandtru** [comment]
Of course it is a basic way. But I want to get errors only on assertions, and this detecting should work whether or not a lint is set.

**Comment by falsandtru** [comment]
I think runtime errors are good error reporting style for power-assert.

```
  assert(n = 0)
           |
           Assignment in the assertion.
```

**Comment by twada** [comment]
I agree with @azu , since power-assert aims to be 100% compatible with native assert.
`AssignmentExpression` is a valid expression in ECMAScript, having return value for it.

It's an ESLint's job to report such a mistake.

It's also a good idea having ESLint rules for assertions. I'm interested in making them. Thanks!

**Comment by falsandtru** [comment]
ok, I'll wait that rule plugin, thanks.

**Comment by falsandtru** [comment]
As a request for that plugin, I want to use it with transpiled TypeScript code. TypeScript is not as good as JavaScript for linting because of the original AST (especially typescript@next).
