### ISSUE TITLE
test files which are not  in the 'test' dir than seems won't work

### ISSUE THREAD

**Issue by kaidiren** [power-assert-js/power-assert#80]
good one:

![image](https://cloud.githubusercontent.com/assets/2025174/23702724/74ce552a-0437-11e7-87b5-87edaf0bf653.png)

bad one:

![image](https://cloud.githubusercontent.com/assets/2025174/23702765/9e95b9f2-0437-11e7-955a-86667ea77203.png)

test with same file: power.js

```
var assert = require('assert');

describe('Array', function(){
    beforeEach(function(){
        this.ary = [1,2,3];
    });
    describe('#indexOf()', function(){
        it('should return index when the value is present', function(){
            var zero = 0, two = 2;
            assert(this.ary.indexOf(zero) === two);
        });
    });
});

```

I have one project that the test files are not in the test dir .

please help me. thanks!

**Comment by kaidiren** [comment]
node version 4.4.0

intelli-espower-loader": "^1.0.1",

"mocha": "^3.2.0",

**Comment by azu** [comment]
Maybe, You could require `power-assert` insteadof `assert` and resolve this issue.

```js
var assert = require('assert');
```

should be

```js
var assert = require('power-assert');
```

**Comment by twada** [comment]
@kaidiren Thank you for your question. If you are using `intelli-espower-loader` and having tests in directory other than `test`, [you have to set test directory in your package.json explicitly](https://github.com/power-assert-js/intelli-espower-loader#1-optional-you-have-to-set-test-directory-to-your-packagejson).

**Comment by kaidiren** [comment]
@twada  thanks!

**Comment by twada** [comment]
I close this issue since this issue seems to be fixed by my answer. Please feel free to reopen this issue if you have any problems.
