### ISSUE TITLE
Type checking with assert.equal

### ISSUE THREAD

**Issue by roginvs** [power-assert-js/power-assert#81]
I found with a surprise that `assert.equal` have both types as 'any' (even the strictEqual too):
```
export function equal(actual:any, expected:any, message?:string):void;
```
Why not do this way:
```
export function equal<T>(actual: T, expected: T, message?:string):void;
```
? It is better to catch any errors on compile time, not in the runtime, is not it?

**Comment by twada** [comment]
@roginvs Thanks for your suggestion.

However, I want power-assert to be completely compliant to [Node's standard assert API](https://nodejs.org/api/assert.html) and do not want users depend on power-assert original API or type definition.

So issues and improvements should be done in [Node.js type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/09a2b06ef71c0a5375d1650c5f5f4e559b6057da/node/index.d.ts#L3646-L3691) first.

**Comment by roginvs** [comment]
Thanks, I asked there
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15162
