### ISSUE TITLE
Seems not working, but I have no idea.

### ISSUE THREAD

**Issue by Pleasurazy** [power-assert-js/power-assert#82]
Hi, I just tried power-assert, it is looks great.

But I can't reproduce power-assert print, I have no idea why.

Could you give me some help?

```
  // It doesn't print
  assert(this.ary.indexOf(zero) === two)
              |   |       |     |   |
              |   |       |     |   2
              |   -1      0     false
              [1,2,3]
```

My package.json

```
{
  "name": "power-assert",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/mocha": "^2.2.40",
    "@types/power-assert": "^1.4.29",
    "espower-typescript": "^8.0.0",
    "intelli-espower-loader": "^1.0.1",
    "mocha": "^3.2.0",
    "power-assert": "^1.4.2"
  },
  "scripts": {
    "test": "mocha --require intelli-espower-loader src/**/*.spec.js"
  }
}
```

index.spec.js

```js
const assert = require('power-assert')

describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert(3 === [1, 2, 3].indexOf(4))
    })
  })
})
```

![image](https://cloud.githubusercontent.com/assets/1500206/24486629/b4caf126-153d-11e7-97e7-1f16148a5838.png)

MacOS 10.12.4
node v6.9.1
yarn 0.20.3

**Comment by twada** [comment]
Hi, thanks for your question @Pleasurazy .

If you are using `intelli-espower-loader` and having tests in directory other than `test`, [you have to set test directory in your package.json explicitly](https://github.com/power-assert-js/intelli-espower-loader#1-optional-you-have-to-set-test-directory-to-your-packagejson).

([Ditto in espower-typescript](https://github.com/power-assert-js/espower-typescript#if-your-tests-are-not-in-test-dir).)

Seems to be the same with #80. So I'd better explain this in [FAQ](https://github.com/power-assert-js/power-assert#faq).

Thanks!

**Comment by Pleasurazy** [comment]
Now it is working with espower-typescript now.

Thank you for your patience. Thanks.

**Comment by twada** [comment]
No problem! I'm glad to hear `power-assert` working well ;)
