### ISSUE TITLE
Do you use package-lock.json?

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#87]
Any plans or thoughts?

**Comment by twada** [comment]
@falsandtru Thank you for your question!

Short answer: Not now. Waiting for getting mature enough.

Generally, I think committing lock file is not a good idea for libraries (good for applications).

However there's an opinion that suggests committing lock files.
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

I agree with it if we can lock devDeps, but not deps.

**Comment by falsandtru** [comment]
I see, thanks for the answer!
